branches:
  only: 
    - next
env:
  global:
    - ANDROID_PACKAGE='camera-debug.apk'
    - ANDROID_PACKAGE_NEXT='camera-debug-next.apk'
    - ANDROID_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/demo/outputs
    - ANDROID_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$ANDROID_PACKAGE_NEXT?overwrite=true"
    - IOS_PACKAGE_NEXT='camera-next.zip'
    - IOS_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/demo/outputs
    - IOS_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$IOS_PACKAGE_NEXT?overwrite=true"

git:
  depth: 1

matrix:
  include:
    - stage: "Build and WebPack"
      os: osx
      env:
        - WebPackiOS="12.0"
        - Type="VanillaJS"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script:
        - cd ../demo && tns platform add ios@next
      script:
        - cd ../demo && npm run build.plugin && npm i && tns build ios --bundle --env.uglify --copy-to "./outputs/demo.app"
        - cd $IOS_PACKAGE_FOLDER && zip -r $IOS_PACKAGE_NEXT demo.app
        - "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $IOS_SAUCE_STORAGE --data-binary @$IOS_PACKAGE_FOLDER/$IOS_PACKAGE_NEXT"
    - os: osx
      env:
        - WebPackiOS="12.0"
        - Type="Angular"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script:
        - cd ../demo-angular && tns platform add ios@next
      script:
        - cd ../src && npm run build && npm pack
        - cd ../demo-angular && tns plugin add ../src/*.tgz
        - npm i && tns build ios --bundle --env.uglify --env.aot
    - language: android
      os: linux
      env:
        - WebPackAndroid="28"
        - Type="VanillaJS"
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      before_script:
        - cd ../demo && tns platform add android@next
      script:
        - cd ../demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot --copy-to "./outputs/app-debug.apk"
        - "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $ANDROID_SAUCE_STORAGE --data-binary @$ANDROID_PACKAGE_FOLDER/app-debug.apk"
    - language: android
      os: linux
      env:
        - WebPackAndroid="28"
        - Type="Angular"
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      before_script:
        - cd ../demo-angular && tns platform add android@next
      script:
        - cd ../src && npm run build
        - cd ../publish && sh pack.sh
        - cd ../demo-angular && tns plugin add ../publish/package/*.tgz
        - npm i && tns build android --bundle --env.uglify --env.snapshot --env.aot
    - env: 
        - BuildAndroid="28"
        - Type="VanillaJS"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      before_script:
        - cd ../demo && tns platform add android@next
      script:
        - cd ../src && npm i && npm run tsc && cd ../demo && tns build android
    - env: 
        - BuildAndroid="28"
        - Type="Angular"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      before_script:
        - cd ../demo-angular && tns platform add android@next
      script:
        - cd ../src && npm i && npm run tsc && cd ../demo-angular && tns build android
    - os: osx
      env: 
        - BuildiOS="12.0"
        - Xcode="10.0"
        - Type="VanillaJS"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script:
        - cd ../demo && tns platform add ios@next
      script: 
        - cd ../src && npm i && npm run tsc && cd ../demo && tns build ios
    - os: osx
      env: 
        - BuildiOS="12.0"
        - Xcode="10.0"
        - Type="Angular"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script:
        - cd ../demo-angular && tns platform add ios@next
      script: 
        - cd ../src && npm i && npm run tsc && cd ../demo-angular && tns build ios
    - stage: "UI Tests"
      env: 
        - Android="23"
      language: node_js
      os: linux
      node_js: "8"
      script:
        - npm i -g appium
        - cd ../demo && npm i
        - travis_retry npm run e2e -- --runType android23 --sauceLab --reuseDevice --appPath $ANDROID_PACKAGE_NEXT
    - os: linux
      env: 
        - iOS="12.0"
      language: node_js 
      node_js: "8"
      script:
        - npm i -g appium
        - cd ../demo && npm i
        - travis_wait travis_retry npm run e2e -- --runType sim.iPhoneX.iOS12 --sauceLab --reuseDevice --appPath $IOS_PACKAGE_NEXT

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        
before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd src
    - npm install tns-core-modules@next -D
    - cd ../demo
    - npm install tns-core-modules@next -P
    - npm install nativescript-dev-webpack@next -D
    - npm install nativescript-dev-typescript@next -D
    - ./node_modules/.bin/update-ns-webpack --deps --configs
    - npm install -D wd@latest
    - cd ../demo-angular
    - npm install tns-core-modules@next -P
    - npm install nativescript-angular@next -P
    - npm install nativescript-dev-webpack@next -D
    - npm install nativescript-dev-typescript@next -D
    - ./node_modules/.bin/update-ns-webpack --deps --configs
    - ./node_modules/.bin/update-app-ng-deps
    - npm install -D wd@latest
