branches:
  only: 
    - next
env:
  global:
    - ANDROID_PACKAGE_JS='camera-debug-js-next.apk'
    - ANDROID_PACKAGE_VUE='camera-debug-vue-next.apk'
    - ANDROID_PACKAGE_FOLDER_JS=$TRAVIS_BUILD_DIR/demo/outputs
    - ANDROID_PACKAGE_FOLDER_VUE=$TRAVIS_BUILD_DIR/demo-vue/outputs
    - ANDROID_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER"
    - IOS_PACKAGE_JS='camera-js-next.zip'
    - IOS_PACKAGE_VUE='camera-vue-next.zip'
    - IOS_PACKAGE_FOLDER_JS=$TRAVIS_BUILD_DIR/demo/outputs
    - IOS_PACKAGE_FOLDER_VUE=$TRAVIS_BUILD_DIR/demo-vue/outputs
    - IOS_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER"

matrix:
  include:
    - stage: "Build and WebPack"
      os: osx
      env:
        - WebPackiOS="12.0"
        - Type="VanillaJS"
      osx_image: xcode10.2
      language: node_js 
      node_js: "10"
      jdk: oraclejdk8
      before_script:
        - cd ../demo && tns platform add ios@next
        - node -p "process.arch"
        - system_profiler SPHardwareDataType | grep "  Memory:"
      script: 
        - cd ../demo && npm run build.plugin
        - npm i && tns build ios --bundle --env.uglify --copy-to "./outputs/demo.app"
        - cd $IOS_PACKAGE_FOLDER_JS && zip -r $IOS_PACKAGE_JS demo.app
        - "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $IOS_SAUCE_STORAGE/$IOS_PACKAGE_JS?overwrite=true --data-binary @$IOS_PACKAGE_FOLDER_JS/$IOS_PACKAGE_JS"
    - os: osx
      env:
        - WebPackiOS="12.0"
        - Type="Angular"
      osx_image: xcode10.2
      language: node_js 
      node_js: "10"
      jdk: oraclejdk8
      before_script:
        - cd ../demo-angular && tns platform add ios@next
        - node -p "process.arch"
        - system_profiler SPHardwareDataType | grep "  Memory:"
      script: 
        - cd ../src && npm run build && npm pack
        - cd ../demo-angular && tns plugin add ../src/*.tgz
        - npm i && tns build ios --bundle --env.uglify --env.aot
    - language: android
      os: linux
      dist: trusty
      env:
        - WebpackAndroid="28"
        - Type="Angular"
      jdk: oraclejdk8
      before_install: nvm install 10
      before_script:
        - cd ../demo-angular && tns platform add android@next
        - node -p "process.arch"
      script:
        - cd ../src && npm run build
        - cd ../publish && sh pack.sh
        - cd ../demo-angular && tns plugin add ../publish/package/*.tgz
        - npm i && tns build android --bundle --env.uglify --env.snapshot --env.aot

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        
before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd demo
    - npm install tns-core-modules@next -P --save-exact
    - npm install tns-platform-declarations@next -D --save-exact
    - npm install nativescript-dev-webpack@next -D --save-exact
    - npm install nativescript-dev-typescript@next -D --save-exact
    - ./node_modules/.bin/update-ns-webpack --deps --configs
    - npx rimraf -- hooks node_modules platforms package-lock.json
    - npm install -D wd@latest
    - cd ../demo-angular
    - npm install tns-core-modules@next -P --save-exact
    - npm install tns-platform-declarations@next -D --save-exact
    - npm install nativescript-angular@next -P --save-exact
    - npm install nativescript-dev-webpack@next -D --save-exact
    - npm install nativescript-dev-typescript@next -D --save-exact
    - ./node_modules/.bin/update-ns-webpack --deps --configs
    - ./node_modules/.bin/update-app-ng-deps
    - npx rimraf -- hooks node_modules platforms package-lock.json
    - npm install -D wd@latest
    - cd ../demo-vue
    - npm install tns-core-modules@next -P --save-exact
    - npm install tns-platform-declarations@next -D --save-exact
    - npm install nativescript-dev-webpack@next -D --save-exact
    - npm install nativescript-dev-typescript@next -D --save-exact
    - ./node_modules/.bin/update-ns-webpack --deps --configs
    - npx rimraf -- hooks node_modules platforms package-lock.json
    - npm install -D wd@latest
